services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=receipts
      - POSTGRES_PASSWORD=receipts
      - POSTGRES_DB=receipts
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: